pipeline:
  stages:
    - preprocess
    - train
    - deploy

preprocessing:
  input_path: "s3://pbg202/data/raw/loan_data.csv"
  output_path: "s3://pbg202/data/processed/preprocessed_data.csv"
  missing_value_strategy: "mean"

training:
  dataset_path: "s3://pbg202/data/processed/preprocessed_data.csv"
  model_output_path: "s3://pbg202/models/"
  algorithm: "MLPClassifier"
  hyperparameters:
    hidden_layer_sizes: [100, 50]
    max_iter: 200
    activation: 'relu'
    solver: 'adam'
    random_state: 42

deployment:
  model_path: "s3://pbg202/models/final_model.pkl"
  endpoint_name: "mlops-endpoint"
  instance_type: "ml.t2.medium"
